### ISSUE TITLE
определить текущий адрес

### ISSUE THREAD

**Issue by NoNews** [yandexmobile/yandexmapkit-android#229]
При старте карт, если нажать на маркер текущего местоположения, появляется адрес/район. Как получить его?

**Comment by NoNews** [comment]
P.S. Проект вообще планируется поддерживаться?

**Comment by saint13** [comment]
Поддерживать планируем.

16 нояб. 2016 г. 15:58 пользователь "Alex Bykov" <notifications@github.com>
написал:

**Comment by NoNews** [comment]
Пробую получать вот так:

` mapController.getOverlayManager().getMyLocation().addMyLocationListener(this);`
```
    @Override
    public void onMyLocationChange(MyLocationItem myLocationItem) {
        mapController.getDownloader().getGeoCode(this, mapController.getGeoPoint(myLocationItem.getScreenPoint()));
    }

    @Override
    public boolean onFinishGeoCode(GeoCode geoCode) {
        if (geoCode != null){
           mapController.getMapView().post(() -> {
//               Log.d("name",geoCode.getDisplayName());
//               Log.d("Subtitle",geoCode.getSubtitle());
//               Log.d("title",geoCode.getTitle());
//               Log.d("title",geoCode.getKind());
               userPoint.setAddress(geoCode.getTitle());
               userPoint.setLat(geoCode.getGeoPoint().getLat());
               userPoint.setLon(geoCode.getGeoPoint().getLon());
               Log.d("User Addresss",userPoint.getAddress());
           });
        }
        return true;
    }
```

Определяет, но очень медленно. На маркере определяется быстрее

**Comment by saint13** [comment]
Да все верно. Могу сказать что в мапките мое место положение такжетработает

16 нояб. 2016 г. 5:21 PM пользователь "Alex Bykov" <notifications@github.com>
написал:

**Comment by NoNews** [comment]
а можно ли как-нибудь вытянуть адрес после того, как текущее местоположение было определено? (когда ещё камера передвигается на маркер). Просто не очень логично получается) текущее местоположение определено, а адреса ещё нет

**Comment by saint13** [comment]
Этого нельзя сделать. Так как запрос на получения адреса запускается только
при клике. Иначе лишние запросы в сеть что нельзя делать.

16 нояб. 2016 г. 5:40 PM пользователь "Alex Bykov" <notifications@github.com>
написал:

а можно ли как-нибудь вытянуть адрес после того, как текущее местоположение
было определено? (когда ещё камера передвигается на маркер). Просто не
очень логично получается) текущее местоположение определено, а адреса ещё
нет

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/yandexmobile/yandexmapkit-android/issues/229#issuecomment-260963859>,
or mute the thread

**Comment by NoNews** [comment]
А можно ли повесить именно на кнопку определение текущих координат+адреса? (как в кнопке findMe)
Пока что получилось это сделать только с  помощью `MyLocationListener`, т.е. при передвижении у меня адрес определяется хорошо. (скорее всего нужно получить текущий MyLocationItem и вызвать getGeocode), как это сделать?

**Comment by NoNews** [comment]
спасибо, получилось
