### ISSUE TITLE
Количество обращений

### ISSUE THREAD

**Issue by NoNews** [yandexmobile/yandexmapkit-android#258]
Здравстауйте.
В описании к YandexMapKit сказано, что через 1 API-key можно прогонять не более чем 25 000 запросов в сутки.

Для определения местоположения обычно использую:
`mMapController.getOverlayManager().getMyLocation().addMyLocationListener(this);`

Вопрос, как именно реализовыван `onMyLocationChanged` ?
Открывается сокет, или же выполняется определенное количество запросов в минуту?
(если определенное количество запросов, то сколько именно?)

**Comment by saint13** [comment]
На место положен е это не распространяется. Возможно это на запрос гео
кодирование.

27 февр. 2017 г. 20:40 пользователь "Alex Bykov" <notifications@github.com>
написал:

Здравстауйте.
В описании к YandexMapKit сказано, что через 1 API-key можно прогонять не
более чем 25 000 запросов в сутки.

Для определения местоположения обычно использую:
mMapController.getOverlayManager().getMyLocation().
addMyLocationListener(this);

Вопрос, как именно реализовыван onMyLocationChanged?
Открывается сокет, или же выполняется определенное количество запросов в
минуту?(если определенное количество запросов, то сколько именно?)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/yandexmobile/yandexmapkit-android/issues/258>, or mute
the thread

**Comment by NoNews** [comment]
@saint13 Спасибо за реактивный ответ!
